// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvjzlrqgbwgsniffygnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2anpscnFnYndnc25pZmZ5Z25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MzI0NjcsImV4cCI6MjA3NzEwODQ2N30.ysRYi8TIgyKoeSRD1Q-pqobSSSRhFZAqLnLj9K6VLNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});